{% set name = "festlex-cmu" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://festvox.org/packed/festival/2.5/festlex_CMU.tar.gz
  sha256: c19430919bca45d5368cd4c82af6153fbcc96a487ebd30b78b5f3c08718b7c07

build:
  number: 0
  noarch: generic

test:
  commands:
    - test -f $PREFIX/share/festival/dicts/cmu/cmulex.scm  # [unix]
    - test -f $PREFIX/share/festival/dicts/cmu/cmudict-0.4.out  # [unix]
    - test -f $PREFIX/share/festival/dicts/cmu/cmu_lts_rules.scm  # [unix]

about:
  home: https://github.com/festvox/festival
  summary: 'CMU dictionary for Festival'
  description: 'CMU dictionary for Festival'
  license: BSD-4-Clause
  license_family: BSD
  license_file: lib/dicts/cmu/COPYING
  doc_url: http://festvox.org
  dev_url: http://festvox.org

extra:
  recipe-maintainers:
    - peci1
